apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifications
  namespace: notifications
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      project: notifications
      service: notifications
