apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gs1-notifications
  namespace: gs1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      project: gs1
      service: gs1-notifications
