apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-db
  namespace: notifications
  labels:
    project: notifications
    service: notifications
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      project: notifications
      service: notifications
      type: db
  template:
    metadata:
      labels:
        project: notifications
        service: notifications
        type: db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: notifications-db
          image: postgres:16.3-alpine
          resources:
            requests:
              memory: '500Mi'
              cpu: '0.5'
            limits:
              memory: '2Gi'
              cpu: '1'
              ephemeral-storage: 5Gi
          envFrom:
            - secretRef:
                name: notifications
          volumeMounts:
            - name: persistent-volume
              mountPath: /var/lib/postgresql/data
              subPath: database
          ports:
            - containerPort: 5432
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: notifications
