apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-app
  namespace: notifications
  labels:
    project: notifications
    service: notifications
    type: app
spec:
  replicas: 2
  selector:
    matchLabels:
      project: notifications
      service: notifications
      type: app
  template:
    metadata:
      labels:
        project: notifications
        service: notifications
        type: app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: notifications-app
          image: a2odev/notifications:latest
          resources:
            requests:
              memory: '250Mi'
              cpu: '0.25'
            limits:
              memory: '500Mi'
              cpu: '0.5'
          envFrom:
            - secretRef:
                name: notifications
            - secretRef:
                name: shared
          ports:
            - containerPort: 3000
