apiVersion: v1
kind: Service
metadata:
  name: gs1-notifications-db
  namespace: gs1
spec:
  selector:
    project: gs1
    service: gs1-notifications
    type: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
